#!/bin/sh -e

prefix="$1"
site="$prefix/usr/share/guile/site"

mkdir -p "$site"
mkdir -p "$prefix/usr/bin"
cp exe/ses "$prefix/usr/bin"
chmod 755 "$prefix/usr/bin/ses"
cp -rt "$site" modules/sph modules/test
chmod -R 755 "$site/sph" "$site/test"
